export const categoriesData = [
    { id: 1, name: 'Technology' },
    { id: 2, name: 'Health' },
    { id: 3, name: 'Education' },
    { id: 4, name: 'Finance' },
    { id: 5, name: 'Travel' },
  ];


  export const postsData = [
    {
      id: "1",
      title: "New Smartphone Model Released",
      content: "A new smartphone model with advanced features has been released.",
      author: "John Doe",
      email: "john.doe@example.com",
      datepublished: "2023-09-20",
      category: "Mobile",
      links: ["https://example.com/news1"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "2",
      title: "AI Breakthrough in Healthcare",
      content: "Artificial intelligence makes a significant breakthrough in healthcare diagnostics.",
      author: "Jane Smith",
      email: "jane.smith@example.com",
      datepublished: "2023-09-19",
      category: "Healthcare",
      links: ["https://example.com/news2"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "3",
      title: "New Features in JavaScript ES2023",
      content: "The latest version of JavaScript introduces new features and improvements.",
      author: "Alice Brown",
      email: "alice.brown@example.com",
      datepublished: "2023-09-18",
      category: "Technology",
      links: ["https://example.com/news3"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "4",
      title: "Climate Change and Its Impact",
      content: "A comprehensive analysis of climate change and its long-term impact on the environment.",
      author: "Robert Green",
      email: "robert.green@example.com",
      datepublished: "2023-09-17",
      category: "Environment",
      links: ["https://example.com/news4"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "5",
      title: "Advancements in Renewable Energy",
      content: "Recent advancements in renewable energy technology and their implications for the future.",
      author: "Emily White",
      email: "emily.white@example.com",
      datepublished: "2023-09-16",
      category: "Energy",
      links: ["https://example.com/news5"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "6",
      title: "Exploring the Depths of the Ocean",
      content: "New discoveries in oceanography reveal the secrets of the deep sea.",
      author: "David Blue",
      email: "david.blue@example.com",
      datepublished: "2023-09-15",
      category: "Science",
      links: ["https://example.com/news6"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    }
  ];
  



  export const posts = [
    // Existing entries...
    {
      id: "1",
      title: "New Smartphone Model Released",
      content: "A new smartphone model with advanced features has been released.",
      author: "John Doe",
      email: "john.doe@example.com",
      datepublished: "2023-09-20",
      category: "Mobile",
      links: ["https://example.com/news1"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "2",
      title: "AI Breakthrough in Healthcare",
      content: "Artificial intelligence makes a significant breakthrough in healthcare diagnostics.",
      author: "Jane Smith",
      email: "jane.smith@example.com",
      datepublished: "2023-09-19",
      category: "Healthcare",
      links: ["https://example.com/news2"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "3",
      title: "New Features in JavaScript ES2023",
      content: "The latest version of JavaScript introduces new features and improvements.",
      author: "Alice Brown",
      email: "alice.brown@example.com",
      datepublished: "2023-09-18",
      category: "Technology",
      links: ["https://example.com/news3"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "4",
      title: "Climate Change and Its Impact",
      content: "A comprehensive analysis of climate change and its long-term impact on the environment.",
      author: "Robert Green",
      email: "robert.green@example.com",
      datepublished: "2023-09-17",
      category: "Environment",
      links: ["https://example.com/news4"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "5",
      title: "Advancements in Renewable Energy",
      content: "Recent advancements in renewable energy technology and their implications for the future.",
      author: "Emily White",
      email: "emily.white@example.com",
      datepublished: "2023-09-16",
      category: "Energy",
      links: ["https://example.com/news5"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "6",
      title: "Exploring the Depths of the Ocean",
      content: "New discoveries in oceanography reveal the secrets of the deep sea.",
      author: "David Blue",
      email: "david.blue@example.com",
      datepublished: "2023-09-15",
      category: "Science",
      links: ["https://example.com/news6"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    // New entries...
    {
      id: "7",
      title: "Revolutionary Battery Technology",
      content: "A new battery technology promises to significantly extend the range of electric vehicles.",
      author: "Laura Green",
      email: "laura.green@example.com",
      datepublished: "2023-09-14",
      category: "Technology",
      links: ["https://example.com/news7"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "8",
      title: "Breakthrough in Quantum Computing",
      content: "Scientists achieve a major breakthrough in quantum computing, paving the way for more powerful computers.",
      author: "Mark Brown",
      email: "mark.brown@example.com",
      datepublished: "2023-09-13",
      category: "Science",
      links: ["https://example.com/news8"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "9",
      title: "New Electric Car Model Unveiled",
      content: "A leading car manufacturer unveils its latest electric car model with cutting-edge features.",
      author: "Anna White",
      email: "anna.white@example.com",
      datepublished: "2023-09-12",
      category: "Automotive",
      links: ["https://example.com/news9"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "10",
      title: "Advances in Biotechnology",
      content: "New advancements in biotechnology offer promising solutions for medical treatments.",
      author: "James Black",
      email: "james.black@example.com",
      datepublished: "2023-09-11",
      category: "Healthcare",
      links: ["https://example.com/news10"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "11",
      title: "Innovations in Agricultural Technology",
      content: "Recent innovations in agricultural technology are improving crop yields and sustainability.",
      author: "Maria Silver",
      email: "maria.silver@example.com",
      datepublished: "2023-09-10",
      category: "Agriculture",
      links: ["https://example.com/news11"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    },
    {
      id: "12",
      title: "Urban Planning for the Future",
      content: "Experts discuss new urban planning strategies for sustainable and livable cities.",
      author: "William Gray",
      email: "william.gray@example.com",
      datepublished: "2023-09-09",
      category: "Urban Planning",
      links: ["https://example.com/news12"],
      thumbnail: "https://images.pexels.com/photos/1616516/pexels-photo-1616516.jpeg",
    }
];
