import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "./provider";
import { Toaster } from "react-hot-toast";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={inter.className}>
        <div className="lg:max-w-[900px] lg:px-16 shadow-md mx-auto px-8 py-8 min-h-screen flex flex-col">
          <Navbar/>
          <div className="flex-auto">
            {children}
          </div>
          <Footer/>
        </div>
        </body>
        <Toaster position="bottom-right" />
      </AuthProvider>
    </html>
  );
}
